services:
  - type: web
    name: newshub-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 15m
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: CLIENT_URL
        sync: false
